# Generated by Django 5.1.1 on 2025-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
